### ISSUE TITLE
Wie soll das Menü funktionieren?

### ISSUE THREAD

**Issue by mgrojo** [HonkiTonk/Civ-Klon#2]
Hallo! Ich habe deine Nachricht auf Reddit gelesen und wollte dein Spiel versuchen. Ich habe den letzten Commit kompiliert, doch ich konnte es nicht richtig laufen. Ich sehe nur ein Sprachmenü, und entweder es funktioniert nicht oder ich weiß es nicht wie.
```
╔═══════╗
║Deutsch║
╚═══════╝
English
```
Meine Konsole ist  Gnome-terminal. Was soll ich dafür benutzen? 

Übrigens, ich bin der Maintainer von ASFML. Ich könnte dir gern helfen, wenn du Schwierigkeiten damit hättest

Entschuldige, wenn mein Deutsch nicht genug gut wäre, ich bin kein Muttersprachler, bin Spanier, aber habe Deutsch gelernt und übe ihn gern.

**Comment by HonkiTonk** [comment]
Hi, das ist ein Fehler der auftritt wenn das Spiel noch keine Einstellungsdatei hat, wird gleich behoben.

This is an error that occurs when the game does not have a settings file and will be fixed immediately.

**Comment by HonkiTonk** [comment]
Der Fehler sollte im aktuellen Commit nicht mehr auftreten. Danke für deinen Bugreport und dein Deutsch ist gut genug um es zu verstehen.

The error should no longer occur in the current commit. Thanks for the bug report and your German is good enough to understand it.

**Comment by mgrojo** [comment]
Danke. Ich werde es bald testen.

**Comment by mgrojo** [comment]
Es läuft gut jetzt.

Ich habe einen Blick geworfen, obwohl ich weiß nicht genau, wie man spielt. Ich habe diese (lustige) Kleinigkeit gesehen:

> The Kasrodiahs, which comes from PLANET NAME, are mammals from the rodent family and have spent large parts of their history creating outstanding **hamburgers** -> _handicrafts_.

Die Übersetzung hat diesen Fehler vermutlich wegen dieser Typo:

> Die von PLANETENNAMEN stammenden Kasrodiahner sind Säugetiere aus der Nagerfamilie und verbrachten große Teile ihrer Geschichte damit herausragende **Hamdwerksarbeiten** ->  _Handwerksarbeiten_ zu kreieren

Happy coding!

**Comment by HonkiTonk** [comment]
Die Steuerung und Übersichtlichkeit ist aktuell eher mäßig, mir war es erst einmal wichtiger funktionierende Systeme zu bauen, aber hoffentlich wird es mit richtiger Grafik dann besser.
Danke für den Hinweis auf den Textfehler, ist korrigiert. Das es nicht mehr unter Windows kompiliert ist mir neu, da werde ich  mal schauen warum.

War bisher auch viel Arbeit, werde aber wohl noch einiges mehr brauchen bis es fertig ist. Ich hoffe es eines Tages verkaufen zu können, mal schauen ob ich das schaffe.

Danke für die Glückwünsche und dir auch noch viel Spaß beim programmieren.

**Comment by mgrojo** [comment]
Das ergibt Sinn. Ich freue mich auf die Version mit Grafik.
